/*
  # Enable Realtime for Signal Tables

  This migration enables Supabase Realtime for the following tables:
  - crypto_signals: Trading signals generated by AI
  - crypto_market_data: Real-time market data
  - api_cache: Cached API responses

  This allows the frontend to receive instant updates when new signals are generated.
*/

ALTER PUBLICATION supabase_realtime ADD TABLE crypto_signals;
ALTER PUBLICATION supabase_realtime ADD TABLE crypto_market_data;
ALTER PUBLICATION supabase_realtime ADD TABLE api_cache;